### ISSUE TITLE
Consider exposing Source's inner String

### ISSUE THREAD

**Issue by Jake-Shadle** [oli-obk/cargo_metadata#95]
Currently `Source(String)` doesn't expose any way to get the inner String other than than doing something nasty like `format!()`, would be nice to either expose the inner String as `pub` or at least provide an `as_ref()/as_str()` to retrieve a reference.

**Comment by oli-obk** [comment]
The reason we can't do this is that if we change the inner representation, we may to be able to give you an `as_str()` reference anymore.

We could have an `into_string` method that may in the future just end up doing formatting itself, but if it's not too problematic I would prefer to close this issue as `wontfix`. You can use `.to_string()` on a `Source`, and, while that uses `format!` internally, that seems API wise to be relatively convenient, even if it maybe does a bit too much work than strictly necessary right now.

**Comment by Jake-Shadle** [comment]
Yah, that's fine, it's obviously not really critical, just felt like a bit of a papercut as, AFAICT, Source is the only type that hides its inner data, as even PackageId exposes the inner `repr`, which can be useful at times, even if it's supposedly opaque. But yes, I'm fine with this being closed as wontfix. :slightly_smiling_face:

**Comment by oli-obk** [comment]
> even PackageId exposes the inner repr

Oh no XD I forgot to fix this in the last breaking change. I guess we can just make all these private things public and at some point do a breaking change where all of them get a better representation, instead of planning now for a refactoring I may never get around to

So... if you open a PR making the field public and giving it some docs, I'll merge it and publish a minor bump

**Comment by Jake-Shadle** [comment]
Ahh ok, cool! :wink:
